game1 = int(input("How many points were scored in the first game?"))
game2 = int(input("How many points were scored in the second game?"))
game3 = int(input("How many points were scored in the third game?"))
game4 = int(input("How many points were scored in the fourth game?"))
game5 = int(input("How many points were scored in the fifth game?"))
average = ((game1+game2+game3+game4+game5)/5)
print("Here is the average number of points scored per game ",average)